"""
mana.journal — what actually happened on each user turn.

The gap this closes
-------------------
`Observation` -- the only thing that may enter the self-model -- is
created in exactly two places, both inside `cognition/curriculum.py`, from
tasks generated by `core/tasks.py` with computed answers. So the entire
self-improvement apparatus (ResearchCycle, choose_mechanism, the genome,
the acceptance gates, the hidden holdout) is pointed at five synthetic
domains, while every defect found in real use lives in the layer between
the person and the tools -- and that layer produces no record at all.

Measured before this module existed: nothing anywhere wrote which tools a
turn called. `grep -rn "tool_calls\\|calls_made" mana/agent_parts/core.py`
returned nothing. The answer text went to memory; the trace of actions did
not go anywhere. Which is why "Открой Notepad++" could answer "Открываю
Notepad++." with zero tool calls and leave no evidence of the discrepancy
behind -- the one fact that makes that failure machine-detectable was the
one fact nobody recorded.

An episode is that fact, written down: the request, every tool the turn
actually dispatched, and what was said back.

What this module does NOT do
----------------------------
It does not judge. Nothing here decides whether a turn went well, blocks
an answer, or feeds the self-model. It records, and it can read back.
Detecting a contradiction between "открываю" and an empty call list is a
separate step with its own decisions, and building it into the recorder
would mean the recorder's own bugs silently rewrite the evidence.

Secrets
-------
Two things written here would carry credentials if written verbatim, and
both are ordinary usage rather than hypothetical:

  * the request -- "Мана запусти 1С базу UT11-ER логин Иванов пароль ..."
    is one of the three 1C scenarios this project was asked to support;
  * a tool's error text -- a failed launch can quote the command line.

So both pass through `scrub()` before they reach the disk. Tool arguments
are never recorded at all: the invariants this journal exists to feed need
which tool ran and whether it succeeded, and arguments are the field most
likely to hold a password with the least to show for the risk.
"""
from __future__ import annotations

import json
from collections import deque
import os
import re
import secrets
import threading
import time
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Any, Dict, Iterator, List, Optional

#: Component version -- see mana/version.py for the bump conventions.
__version__ = "1.0"

#: Rotate at this size and keep one previous file. A journal that grows
#: without bound on a machine that runs for months is a defect, and one
#: that keeps only the current file loses exactly the history the first
#: measurement needs.
MAX_BYTES = 8 * 1024 * 1024

#: Long free text is truncated rather than dropped: the beginning of an
#: answer is enough to tell a narration from a refusal, and whole essays
#: multiplied by every turn are what makes a log unreadable.
MAX_TEXT = 2000
MAX_ERROR = 300

#: Where a turn was answered from. Recorded because the routes have
#: genuinely different failure modes -- `app_intent` builds its reply from
#: a tool outcome, `pipeline` builds it from a model -- and an invariant
#: that could not tell them apart would be comparing different things.
ROUTES = ("app_intent", "pipeline", "clarification", "memory_write")

#: Explicit labels only. A pattern general enough to catch an unlabelled
#: secret is general enough to redact ordinary content, and a journal that
#: quietly mangles the request is worse than one that keeps it.
_SECRETS = (
    re.compile(r"(парол[ья][:=\s]+)(\S+)", re.IGNORECASE),
    re.compile(r"(password[:=\s]+)(\S+)", re.IGNORECASE),
    re.compile(r"(pwd[:=\s]+)(\S+)", re.IGNORECASE),
    re.compile(r"(/P)(\S+)"),                      # 1C command line
    re.compile(r"(api[_-]?key[:=\s]+)(\S+)", re.IGNORECASE),
    # Both separators: Groq issues `gsk_...` where OpenAI issues `sk-...`,
    # and a pattern that assumed the hyphen let a live Groq key straight
    # through. Found by the test, not by reading it.
    re.compile(r"()\b((?:sk|gsk|xai|csk)[-_][A-Za-z0-9_-]{12,})"),
)

REDACTED = "***"


def scrub(text: str) -> str:
    """Remove credentials that ordinary use puts into ordinary text."""
    out = str(text or "")
    for pattern in _SECRETS:
        out = pattern.sub(lambda m: m.group(1) + REDACTED, out)
    return out


def _clip(text: str, limit: int) -> str:
    s = str(text or "")
    return s if len(s) <= limit else s[:limit] + "…"


@dataclass(frozen=True)
class ToolCall:
    """One dispatch through the registry. No arguments -- see module doc."""
    tool: str
    ok: bool
    latency: float = 0.0
    error: str = ""
    #: What the tool observed afterwards: confirmed, contradicted,
    #: unobserved, or empty when the tool does not observe at all. Kept
    #: apart from `ok`, which only ever meant that the call returned --
    #: an episode where every call is ok and every verdict is
    #: "contradicted" is a turn that did nothing it claimed to do, and
    #: before this the record could not tell the two apart.
    verified: str = ""

    def as_dict(self) -> Dict[str, Any]:
        return {"tool": self.tool, "ok": self.ok,
                "latency": round(self.latency, 4), "error": self.error,
                "verified": self.verified}


@dataclass
class Episode:
    """One user turn, with what it did.

    `calls` is the field this whole module exists for. Everything else is
    context for reading it back.
    """
    episode_id: str
    session: str
    started: float
    request: str
    answer: str = ""
    route: str = "pipeline"
    calls: List[ToolCall] = field(default_factory=list)
    latency: float = 0.0
    version: str = ""

    def as_dict(self) -> Dict[str, Any]:
        d = asdict(self)
        d["calls"] = [c.as_dict() for c in self.calls]
        return d

    @classmethod
    def from_dict(cls, row: Dict[str, Any]) -> "Episode":
        calls = [ToolCall(tool=str(c.get("tool", "")), ok=bool(c.get("ok")),
                          latency=float(c.get("latency") or 0.0),
                          error=str(c.get("error") or ""),
                          verified=str(c.get("verified") or ""))
                 for c in (row.get("calls") or [])]
        return cls(episode_id=str(row.get("episode_id", "")),
                   session=str(row.get("session", "")),
                   started=float(row.get("started") or 0.0),
                   request=str(row.get("request") or ""),
                   answer=str(row.get("answer") or ""),
                   route=str(row.get("route") or "pipeline"),
                   calls=calls,
                   latency=float(row.get("latency") or 0.0),
                   version=str(row.get("version") or ""))

    # ---------- what a reader asks of an episode ----------

    def tools_used(self) -> List[str]:
        return [c.tool for c in self.calls]

    def acted(self) -> bool:
        """Did anything succeed? The plain form of "did it do something"."""
        return any(c.ok for c in self.calls)

    def contradicted(self) -> List[str]:
        """Tools that ran and left the machine in the wrong state.

        A mechanical failure with nothing interpreted: the tool itself
        compared what it was asked for against what it found. This is the
        cheapest evidence in the journal and the only kind that needs no
        model to read it.
        """
        return [c.tool for c in self.calls if c.verified == "contradicted"]

    def unverified(self) -> List[str]:
        """Tools that acted and never looked at the result.

        Reported separately from `contradicted` because it is a different
        thing to fix: not a wrong action, an unobserved one.
        """
        return [c.tool for c in self.calls if c.verified == "unobserved"]


#: How many recent episodes stay in memory for the live check. Small:
#: the only reader asks for one session's last few turns, and a
#: process that runs for weeks must not grow a list of everything it
#: ever answered.
RECENT_EPISODES = 24

#: Where the journal lives when nobody says otherwise. Kept in step with
#: `Config.journal_path`, which is what the agent actually passes; this
#: default is for readers (`--journal`) that show the record without
#: constructing an agent.
DEFAULT_RELATIVE = "journal/episodes.jsonl"


def default_path() -> Path:
    """Beside the rest of the user's state, not beside the executable."""
    from .paths import resolve_data_path
    return resolve_data_path(DEFAULT_RELATIVE)


class Recorder:
    """Collects the calls of one turn, on one thread.

    Per thread, deliberately. The registry is shared and a background
    research cycle can be calling tools while a person types; an episode
    that swept those in would attribute work to a turn that never did it.
    A thread with no episode open records nothing, which is the correct
    behaviour for every caller that is not a user turn.
    """

    def __init__(self, journal: "Journal", episode: Episode) -> None:
        self._journal = journal
        self.episode = episode

    def note(self, tool: str, ok: bool, latency: float, error: str = "",
             verified: str = "") -> None:
        self.episode.calls.append(ToolCall(
            tool=str(tool), ok=bool(ok), latency=float(latency or 0.0),
            error=_clip(scrub(error), MAX_ERROR),
            verified=str(verified or "")))

    def close(self, answer: str, route: str = "pipeline") -> Episode:
        ep = self.episode
        ep.answer = _clip(scrub(answer), MAX_TEXT)
        ep.route = route if route in ROUTES else "pipeline"
        ep.latency = max(0.0, time.time() - ep.started)
        self._journal.write(ep)
        return ep


class Journal:
    """Append-only episodes on disk, and a way to read them back.

    Every write is wrapped: a journal that cannot write must never be the
    reason a user's turn fails. It is evidence, not machinery.
    """

    def __init__(self, path: Optional[Path | str] = None,
                 version: str = "") -> None:
        self.path = Path(path) if path else default_path()
        self.version = str(version or "")
        self._lock = threading.Lock()
        self._local = threading.local()
        self._recent: "deque[Episode]" = deque(maxlen=RECENT_EPISODES)

    # ---------- recording ----------

    def open(self, request: str, session: str = "") -> Recorder:
        """Start an episode on this thread. Always returns a recorder."""
        episode = Episode(
            episode_id=f"{int(time.time() * 1000):x}-{secrets.token_hex(3)}",
            session=str(session or ""), started=time.time(),
            request=_clip(scrub(request), MAX_TEXT), version=self.version)
        recorder = Recorder(self, episode)
        self._local.recorder = recorder
        return recorder

    def current(self) -> Optional[Recorder]:
        """The episode open on this thread, if there is one."""
        return getattr(self._local, "recorder", None)

    def finish(self, answer: str, route: str = "pipeline") -> Optional[Episode]:
        """Close this thread's episode. None when none was open."""
        recorder = self.current()
        if recorder is None:
            return None
        self._local.recorder = None
        try:
            return recorder.close(answer, route)
        except Exception:
            return None

    def abandon(self) -> None:
        """Drop this thread's episode without writing it."""
        self._local.recorder = None

    def note_call(self, tool: str, ok: bool, latency: float,
                  error: str = "", verified: str = "") -> None:
        """Registry hook. Silent when this thread has no episode open."""
        recorder = self.current()
        if recorder is None:
            return
        try:
            recorder.note(tool, ok, latency, error, verified)
        except Exception:
            pass

    def session_recent(self, session: str, limit: int = RECENT_EPISODES,
                       exclude: str = "") -> List[Episode]:
        """The last episodes of one session, from memory, oldest first.

        From memory rather than off disk. This is read once per turn, the
        file is capped at 8 MB plus a rotation, and a check that costs a
        full file read every turn is a check somebody eventually switches
        off. What it misses -- episodes from before this process started
        -- is the correct trade for a live check: the full record is
        still there for `--findings` to walk.
        """
        rows = [e for e in list(self._recent)
                if e.session == session and e.episode_id != exclude]
        return rows[-limit:] if limit and limit > 0 else rows

    def write(self, episode: Episode) -> bool:
        # Kept in memory whether or not the disk write works: the live
        # check that reads this should not go blind because a directory
        # is read-only.
        self._recent.append(episode)
        line = json.dumps(episode.as_dict(), ensure_ascii=False)
        with self._lock:
            try:
                self.path.parent.mkdir(parents=True, exist_ok=True)
                self._rotate_if_needed()
                with self.path.open("a", encoding="utf-8") as fh:
                    fh.write(line + "\n")
                return True
            except Exception:
                return False

    def _rotate_if_needed(self) -> None:
        try:
            if self.path.exists() and self.path.stat().st_size >= MAX_BYTES:
                previous = self.path.with_suffix(self.path.suffix + ".1")
                if previous.exists():
                    previous.unlink()
                os.replace(self.path, previous)
        except Exception:
            pass

    # ---------- reading back ----------

    def episodes(self, limit: int = 0,
                 include_rotated: bool = True) -> List[Episode]:
        """Episodes oldest-first, the most recent `limit` of them.

        A malformed line is skipped rather than raising: a journal is
        appended to from several threads over months of running, and one
        truncated write must not make the rest unreadable.
        """
        rows: List[Episode] = []
        files: List[Path] = []
        if include_rotated:
            previous = self.path.with_suffix(self.path.suffix + ".1")
            if previous.exists():
                files.append(previous)
        files.append(self.path)
        for f in files:
            for row in self._read_file(f):
                rows.append(row)
        return rows[-limit:] if limit and limit > 0 else rows

    @staticmethod
    def _read_file(path: Path) -> Iterator[Episode]:
        try:
            handle = path.open("r", encoding="utf-8")
        except Exception:
            return
        with handle:
            for line in handle:
                line = line.strip()
                if not line:
                    continue
                try:
                    yield Episode.from_dict(json.loads(line))
                except Exception:
                    continue

    def contradicted_calls(self, limit: int = 0) -> List[Dict[str, str]]:
        """Every recorded call whose tool says it did not do what it was
        asked to do.

        Mechanical evidence with nothing interpreted: the tool compared
        the state it was asked for against the state it found. Kept here
        so that a reader -- a person, or the finding generator -- does not
        have to walk the episodes to ask the one question the record was
        extended to answer.
        """
        out: List[Dict[str, str]] = []
        for episode in self.episodes(limit=limit):
            for call in episode.calls:
                if call.verified == "contradicted":
                    out.append({"episode": episode.episode_id,
                                "request": episode.request,
                                "answer": episode.answer,
                                "tool": call.tool})
        return out

    def stats(self, limit: int = 0) -> Dict[str, Any]:
        """A shape of the record, for looking at what has accumulated.

        Deliberately descriptive. No rates, no verdicts, nothing that
        reads as a judgement on how well MANA is doing -- this counts
        what is there so a person can decide whether it is enough to
        measure anything with.
        """
        episodes = self.episodes(limit=limit)
        by_route: Dict[str, int] = {}
        by_tool: Dict[str, int] = {}
        silent = 0
        for ep in episodes:
            by_route[ep.route] = by_route.get(ep.route, 0) + 1
            for call in ep.calls:
                by_tool[call.tool] = by_tool.get(call.tool, 0) + 1
            if not ep.calls:
                silent += 1
        return {
            "path": str(self.path),
            "exists": self.path.exists(),
            "episodes": len(episodes),
            "sessions": len({ep.session for ep in episodes if ep.session}),
            "with_no_calls": silent,
            "by_route": by_route,
            "by_tool": dict(sorted(by_tool.items(),
                                   key=lambda kv: -kv[1])),
            "first": episodes[0].started if episodes else 0.0,
            "last": episodes[-1].started if episodes else 0.0,
        }
